# Generated by Django 4.2.1 on 2023-05-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_name',
        ),
    ]
